# Generated by Django 5.1.2 on 2024-11-15 03:08

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'Borrador'), ('to_quote', 'Por cotizar'), ('paid', 'Pagado'), ('in_progress', 'En progreso'), ('delivered', 'Entregado')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Total discount', max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total price', max_digits=10, null=True)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created'],
            },
        ),
    ]
