# Generated by Django 5.1.2 on 2024-11-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderline',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
