services:
  backend:
    image: bootcamp-django:1.0.0
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: