# Generated by Django 5.1.2 on 2024-11-06 08:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('to_quote', 'Por cotizar'), ('quoted', 'Cotizado'), ('in_progress', 'En progreso'), ('done', 'Listo para recoger')], default='to_quote', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='services/')),
                ('thickness', models.DecimalField(decimal_places=2, help_text='mm', max_digits=10)),
                ('fold_number', models.PositiveIntegerField(blank=True, default=0, help_text='Number of folds')),
                ('units', models.PositiveIntegerField(default=1, help_text='Quantity of units')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Total discount', max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total price', max_digits=10, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='products.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='orders.order')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
