# Generated by Django 5.1.2 on 2024-11-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
